image:
  repository: ###ZARF_REGISTRY###/ironbank/rook/ceph
  # renovate: image=registry1.dso.mil/ironbank/rook/ceph
  tag: v1.11.8

csi:
  cephFSKernelMountOptions: "ms_mode=secure"

  readAffinity:
    enabled: true

  cephcsi:
    # renovate: image=registry1.dso.mil/ironbank/opensource/ceph/ceph-csi
    image: ###ZARF_REGISTRY###/ironbank/opensource/ceph/ceph-csi:v3.8.0

  registrar:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar:v2.8.1

  provisioner:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner:v3.5.2

  snapshotter:
    # renovate: image=registry.k8s.io/sig-storage/csi-snapshotter
    image: ###ZARF_REGISTRY###/sig-storage/csi-snapshotter:v6.2.2

  attacher:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher:v4.3.2

  resizer:
    # renovate: image=registry.k8s.io/sig-storage/csi-resizer
    image: ###ZARF_REGISTRY###/sig-storage/csi-resizer:v1.8.2

imagePullSecrets:
  - name: private-registry

# -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in environments with SELinux restrictions.
hostpathRequiresPrivileged: true
